# Generated by Django 2.0.5 on 2018-05-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180504_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='category',
            new_name='trademark',
        ),
    ]
